import {
  LayoutDashboard,
  Users,
  ArrowLeftRight,
  Calculator,
  Globe,
  Scissors,
  FileText,
  BookOpen,
  Cpu,
  Receipt,
  BarChart3,
  TrendingUp,
  Percent,
  Landmark,
  Wallet,
  Clock,
  Upload,
  ScanLine,
  Plug,
  Building2,
  Network,
  Handshake,
  Ticket,
  Scale,
  MessageSquare,
  Sparkles,
  ShieldCheck,
  AlertTriangle,
  Database,
  FileCheck,
  CreditCard,
  Settings,
  Server,
  UserCog,
} from "lucide-react";

import type { NavGroup } from "@/types/navigation";

export const dashboardNavigation: NavGroup[] = [
  {
    id: "main",
    title: "Main",
    arabicTitle: "الرئيسية",
    items: [
      {
        title: "Dashboard",
        arabicTitle: "لوحة التحكم",
        href: "/dashboard",
        icon: LayoutDashboard,
      },
    ],
  },
  {
    id: "operations",
    title: "Operations",
    arabicTitle: "العمليات",
    items: [
      {
        title: "Clients",
        arabicTitle: "العملاء",
        href: "/clients",
        icon: Users,
      },
      {
        title: "Transactions",
        arabicTitle: "المعاملات",
        href: "/transactions",
        icon: ArrowLeftRight,
      },
      {
        title: "Remittance Pricing",
        arabicTitle: "تسعير الحوالات",
        href: "/remittance-pricing",
        icon: Calculator,
      },
      {
        title: "Quotes",
        arabicTitle: "عروض الأسعار",
        href: "/quotes",
        icon: FileText,
      },
      {
        title: "Invoices & Documents",
        arabicTitle: "الفواتير والمستندات",
        href: "/invoices-documents",
        icon: Receipt,
      },
      {
        title: "Reports",
        arabicTitle: "التقارير",
        href: "/reports",
        icon: BarChart3,
      },
    ],
  },
  {
    id: "financial",
    title: "Financial",
    arabicTitle: "المالية",
    items: [
      {
        title: "Accounting",
        arabicTitle: "المحاسبة",
        href: "/accounting",
        icon: BookOpen,
      },
      {
        title: "FlashCount",
        arabicTitle: "فلاش كاونت",
        href: "/flashcount",
        icon: Cpu,
      },
      {
        title: "Country Price Lists",
        arabicTitle: "قوائم الأسعار",
        href: "/country-price-lists",
        icon: Globe,
      },
      {
        title: "Cut Rules",
        arabicTitle: "قواعد القص",
        href: "/cut-rules",
        icon: Scissors,
      },
      {
        title: "Exchange Rates",
        arabicTitle: "أسعار الصرف",
        href: "/exchange-rates",
        icon: TrendingUp,
      },
      {
        title: "Fees & Pricing",
        arabicTitle: "الرسوم والتسعير",
        href: "/fees-pricing",
        icon: Percent,
      },
      {
        title: "Capital & Liquidity",
        arabicTitle: "رأس المال والسيولة",
        href: "/capital-liquidity",
        icon: Landmark,
      },
      {
        title: "Daily Closing",
        arabicTitle: "الإغلاق اليومي",
        href: "/daily-closing",
        icon: Clock,
      },
      {
        title: "Cash & Shifts",
        arabicTitle: "النقد والورديات",
        href: "/cash-shifts",
        icon: Wallet,
      },
    ],
  },
  {
    id: "network",
    title: "Network",
    arabicTitle: "الشبكة",
    items: [
      {
        title: "Business Network",
        arabicTitle: "الشبكة التجارية",
        href: "/business-network",
        icon: Building2,
      },
      {
        title: "Office Services",
        arabicTitle: "خدمات المكاتب",
        href: "/office-services",
        icon: Network,
      },
      {
        title: "Partner Discovery",
        arabicTitle: "اكتشاف الشركاء",
        href: "/partner-discovery",
        icon: Handshake,
      },
      {
        title: "Partner Requests",
        arabicTitle: "طلبات الشراكة",
        href: "/partner-requests",
        icon: UserCog,
      },
      {
        title: "Deal Tickets",
        arabicTitle: "تذاكر الصفقات",
        href: "/deal-tickets",
        icon: Ticket,
      },
      {
        title: "Settlements",
        arabicTitle: "التسويات",
        href: "/settlements",
        icon: Scale,
      },
    ],
  },
  {
    id: "intelligence",
    title: "Intelligence",
    arabicTitle: "الذكاء",
    items: [
      {
        title: "Smart Import",
        arabicTitle: "الاستيراد الذكي",
        href: "/smart-import",
        icon: Upload,
      },
      {
        title: "Receipt Scanner",
        arabicTitle: "ماسح الإيصالات",
        href: "/receipt-scanner",
        icon: ScanLine,
      },
      {
        title: "AI Center",
        arabicTitle: "الذكاء الاصطناعي",
        href: "/ai-center",
        icon: Sparkles,
      },
      {
        title: "FlashAudit",
        arabicTitle: "التدقيق",
        href: "/flashaudit",
        icon: ShieldCheck,
      },
      {
        title: "Data Quality",
        arabicTitle: "جودة البيانات",
        href: "/data-quality",
        icon: Database,
      },
    ],
  },
  {
    id: "admin",
    title: "Admin",
    arabicTitle: "الإدارة",
    items: [
      {
        title: "Administration",
        arabicTitle: "مركز الإدارة",
        href: "/administration",
        icon: UserCog,
      },
      {
        title: "Compliance & Verification",
        arabicTitle: "الامتثال والتحقق",
        href: "/compliance-verification",
        icon: FileCheck,
      },
      {
        title: "Incidents & Disputes",
        arabicTitle: "الحوادث والنزاعات",
        href: "/incidents-disputes",
        icon: AlertTriangle,
      },
      {
        title: "Subscriptions & Billing",
        arabicTitle: "الاشتراكات",
        href: "/subscriptions-billing",
        icon: CreditCard,
      },
      {
        title: "Settings",
        arabicTitle: "الإعدادات",
        href: "/settings",
        icon: Settings,
      },
      {
        title: "System Operations",
        arabicTitle: "عمليات النظام",
        href: "/system-operations",
        icon: Server,
      },
      {
        title: "Integrations",
        arabicTitle: "التكامل",
        href: "/integrations",
        icon: Plug,
      },
      {
        title: "Communication",
        arabicTitle: "التواصل",
        href: "/communication",
        icon: MessageSquare,
      },
    ],
  },
];

export const publicNavigation = [
  { title: "Home", arabicTitle: "الرئيسية", href: "/" },
  { title: "About", arabicTitle: "عن المنصة", href: "/about" },
  { title: "Offices", arabicTitle: "المكاتب", href: "/offices" },
  { title: "Login", arabicTitle: "تسجيل الدخول", href: "/login" },
] as const;
